insert into artifact (artifactID, anomalyID, name, price, health_change, speed_change, spawn_probability, ownerID) values (1, 1, 'ATOM', 33735, 10, 49, 99, null);
insert into artifact (artifactID, anomalyID, name, price, health_change, speed_change, spawn_probability, ownerID) values (2, 2, 'BALL', 25485, 6, 46, 16, null);
insert into artifact (artifactID, anomalyID, name, price, health_change, speed_change, spawn_probability, ownerID) values (3, 3, 'BUBBLE', 32045, 28, 5, 64, 94);
insert into artifact (artifactID, anomalyID, name, price, health_change, speed_change, spawn_probability, ownerID) values (4, 4, 'BAT', 1255, 20, 38, 65, null);
insert into artifact (artifactID, anomalyID, name, price, health_change, speed_change, spawn_probability, ownerID) values (5, 5, 'BLACK STONE', 632, 6, 21, 3, null);
insert into artifact (artifactID, anomalyID, name, price, health_change, speed_change, spawn_probability, ownerID) values (6, 6, 'BLACK ANGEL', 10952, 34, 40, 15, null);
insert into artifact (artifactID, anomalyID, name, price, health_change, speed_change, spawn_probability, ownerID) values (7, 7, 'BLACK SPRAY', 7604, 24, 8, 81, 14);
insert into artifact (artifactID, anomalyID, name, price, health_change, speed_change, spawn_probability, ownerID) values (8, 8, 'STONE BLOOD', 37138, 28, 26, 12, null);
insert into artifact (artifactID, anomalyID, name, price, health_change, speed_change, spawn_probability, ownerID) values (9, 9, 'BRACELET', 35617, 39, 50, 17, 48);
insert into artifact (artifactID, anomalyID, name, price, health_change, speed_change, spawn_probability, ownerID) values (10, 10, 'CELL', 21695, 21, 22, 10, 26);
insert into artifact (artifactID, anomalyID, name, price, health_change, speed_change, spawn_probability, ownerID) values (11, 11, 'CHAIN', 10692, 23, 32, 54, null);
insert into artifact (artifactID, anomalyID, name, price, health_change, speed_change, spawn_probability, ownerID) values (12, 12, 'COCOON', 25332, 9, 30, 3, 92);
insert into artifact (artifactID, anomalyID, name, price, health_change, speed_change, spawn_probability, ownerID) values (13, 13, 'COMPASS', 35040, 9, 20, 16, 98);
insert into artifact (artifactID, anomalyID, name, price, health_change, speed_change, spawn_probability, ownerID) values (14, 14, 'CRYSTAL', 35419, 37, 22, 48, 24);
insert into artifact (artifactID, anomalyID, name, price, health_change, speed_change, spawn_probability, ownerID) values (15, 15, 'STONE FLOWER', 14393, 30, 0, 11, 61);
insert into artifact (artifactID, anomalyID, name, price, health_change, speed_change, spawn_probability, ownerID) values (16, 16, 'DEATH LAMP', 2594, 3, 21, 95, 7);
insert into artifact (artifactID, anomalyID, name, price, health_change, speed_change, spawn_probability, ownerID) values (17, 17, 'DRAGON''S EYE', 35211, 22, 26, 4, null);
insert into artifact (artifactID, anomalyID, name, price, health_change, speed_change, spawn_probability, ownerID) values (18, 18, 'BATTERY', 35825, 47, 46, 22, 43);
insert into artifact (artifactID, anomalyID, name, price, health_change, speed_change, spawn_probability, ownerID) values (19, 19, 'SHELL', 5367, 0, 16, 19, 18);
insert into artifact (artifactID, anomalyID, name, price, health_change, speed_change, spawn_probability, ownerID) values (20, 20, 'MAMA''S BEADS', 37438, 48, 30, 39, 12);
insert into artifact (artifactID, anomalyID, name, price, health_change, speed_change, spawn_probability, ownerID) values (21, 21, 'HEART', 32650, 27, 24, 10, 17);
insert into artifact (artifactID, anomalyID, name, price, health_change, speed_change, spawn_probability, ownerID) values (22, 22, 'FLASH', 5383, 41, 43, 40, 68);
insert into artifact (artifactID, anomalyID, name, price, health_change, speed_change, spawn_probability, ownerID) values (23, 23, 'MOONLIGHT', 15560, 17, 6, 94, 75);
insert into artifact (artifactID, anomalyID, name, price, health_change, speed_change, spawn_probability, ownerID) values (24, 24, 'SPARKLER', 22888, 16, 12, 47, 72);
insert into artifact (artifactID, anomalyID, name, price, health_change, speed_change, spawn_probability, ownerID) values (25, 25, 'ELECTRON', 3607, 29, 8, 52, 31);
insert into artifact (artifactID, anomalyID, name, price, health_change, speed_change, spawn_probability, ownerID) values (26, 26, 'EMPTY', 10052, 46, 29, 28, 75);
insert into artifact (artifactID, anomalyID, name, price, health_change, speed_change, spawn_probability, ownerID) values (27, 27, 'EYE', 27203, 26, 4, 0, null);
insert into artifact (artifactID, anomalyID, name, price, health_change, speed_change, spawn_probability, ownerID) values (28, 28, 'FLAME', 19790, 18, 19, 46, 13);
insert into artifact (artifactID, anomalyID, name, price, health_change, speed_change, spawn_probability, ownerID) values (29, 29, 'KNOT', 24975, 29, 18, 71, null);
insert into artifact (artifactID, anomalyID, name, price, health_change, speed_change, spawn_probability, ownerID) values (30, 30, 'FIREBALL', 11013, 5, 2, 10, 9);
insert into artifact (artifactID, anomalyID, name, price, health_change, speed_change, spawn_probability, ownerID) values (31, 31, 'LAMP', 10840, 24, 26, 100, 85);
insert into artifact (artifactID, anomalyID, name, price, health_change, speed_change, spawn_probability, ownerID) values (32, 32, 'FOUNTAIN', 31207, 23, 2, 33, 61);
insert into artifact (artifactID, anomalyID, name, price, health_change, speed_change, spawn_probability, ownerID) values (33, 33, 'FULL EMPTY', 31709, 26, 12, 95, null);
insert into artifact (artifactID, anomalyID, name, price, health_change, speed_change, spawn_probability, ownerID) values (34, 34, 'KOLOBOK', 12354, 1, 23, 19, null);
insert into artifact (artifactID, anomalyID, name, price, health_change, speed_change, spawn_probability, ownerID) values (35, 35, 'GENERATOR', 32673, 12, 46, 15, 79);
insert into artifact (artifactID, anomalyID, name, price, health_change, speed_change, spawn_probability, ownerID) values (36, 36, 'FIREFLY', 8119, 48, 13, 1, 94);
insert into artifact (artifactID, anomalyID, name, price, health_change, speed_change, spawn_probability, ownerID) values (37, 37, 'GOLDFISH', 2100, 39, 44, 35, 61);
insert into artifact (artifactID, anomalyID, name, price, health_change, speed_change, spawn_probability, ownerID) values (38, 38, 'GRAPES', 4499, 37, 5, 99, 62);
insert into artifact (artifactID, anomalyID, name, price, health_change, speed_change, spawn_probability, ownerID) values (39, 39, 'GRAVI', 26444, 9, 1, 98, null);
insert into artifact (artifactID, anomalyID, name, price, health_change, speed_change, spawn_probability, ownerID) values (40, 40, 'SNOWFLAKE', 12177, 2, 30, 4, 23);
insert into artifact (artifactID, anomalyID, name, price, health_change, speed_change, spawn_probability, ownerID) values (41, 41, 'ITCHER', 35784, 20, 36, 61, 94);
insert into artifact (artifactID, anomalyID, name, price, health_change, speed_change, spawn_probability, ownerID) values (42, 42, 'SOURPUSS', 11134, 15, 20, 24, null);
insert into artifact (artifactID, anomalyID, name, price, health_change, speed_change, spawn_probability, ownerID) values (43, 43, 'CLAW', 29436, 39, 23, 47, 16);
insert into artifact (artifactID, anomalyID, name, price, health_change, speed_change, spawn_probability, ownerID) values (44, 44, 'BEACON', 27370, 47, 1, 40, null);
insert into artifact (artifactID, anomalyID, name, price, health_change, speed_change, spawn_probability, ownerID) values (45, 45, 'LOBSTER EYES', 20986, 41, 21, 28, 56);
insert into artifact (artifactID, anomalyID, name, price, health_change, speed_change, spawn_probability, ownerID) values (46, 46, 'MEDAL', 15808, 25, 32, 46, 37);
insert into artifact (artifactID, anomalyID, name, price, health_change, speed_change, spawn_probability, ownerID) values (47, 47, 'JELLYFISH', 23562, 3, 22, 70, 76);
insert into artifact (artifactID, anomalyID, name, price, health_change, speed_change, spawn_probability, ownerID) values (48, 48, 'MEAT CHUNK', 34958, 30, 40, 93, null);
insert into artifact (artifactID, anomalyID, name, price, health_change, speed_change, spawn_probability, ownerID) values (49, 49, 'MOSS', 19013, 3, 39, 67, 53);
insert into artifact (artifactID, anomalyID, name, price, health_change, speed_change, spawn_probability, ownerID) values (50, 50, 'VOLAT EMERALD', 15105, 36, 43, 61, 99);
insert into artifact (artifactID, anomalyID, name, price, health_change, speed_change, spawn_probability, ownerID) values (51, 51, 'NIGHTSTAR', 20837, 9, 11, 46, 40);
insert into artifact (artifactID, anomalyID, name, price, health_change, speed_change, spawn_probability, ownerID) values (52, 52, 'HEART OF THE OASIS', 23308, 12, 13, 67, null);
insert into artifact (artifactID, anomalyID, name, price, health_change, speed_change, spawn_probability, ownerID) values (53, 53, 'MOON', 31363, 49, 34, 100, null);
insert into artifact (artifactID, anomalyID, name, price, health_change, speed_change, spawn_probability, ownerID) values (54, 54, 'PIN', 16044, 1, 9, 38, null);
insert into artifact (artifactID, anomalyID, name, price, health_change, speed_change, spawn_probability, ownerID) values (55, 55, 'THRISTLE', 7225, 28, 25, 21, 24);
insert into artifact (artifactID, anomalyID, name, price, health_change, speed_change, spawn_probability, ownerID) values (56, 56, 'RING', 9829, 21, 21, 94, 60);
insert into artifact (artifactID, anomalyID, name, price, health_change, speed_change, spawn_probability, ownerID) values (57, 57, 'SANDSTONE', 14182, 40, 23, 86, null);
insert into artifact (artifactID, anomalyID, name, price, health_change, speed_change, spawn_probability, ownerID) values (58, 58, 'SERAPHIM', 21151, 41, 33, 12, 72);
insert into artifact (artifactID, anomalyID, name, price, health_change, speed_change, spawn_probability, ownerID) values (59, 59, 'SIGNET', 33993, 12, 27, 9, 96);
insert into artifact (artifactID, anomalyID, name, price, health_change, speed_change, spawn_probability, ownerID) values (60, 60, 'MISER''S SKULL', 14591, 3, 29, 16, 91);
insert into artifact (artifactID, anomalyID, name, price, health_change, speed_change, spawn_probability, ownerID) values (61, 61, 'SOUL', 10452, 34, 33, 30, 79);
insert into artifact (artifactID, anomalyID, name, price, health_change, speed_change, spawn_probability, ownerID) values (62, 62, 'SPIKE', 38095, 12, 9, 83, 85);
insert into artifact (artifactID, anomalyID, name, price, health_change, speed_change, spawn_probability, ownerID) values (63, 63, 'SPONGE', 17452, 37, 27, 99, 32);
insert into artifact (artifactID, anomalyID, name, price, health_change, speed_change, spawn_probability, ownerID) values (64, 64, 'PHANTOM STAR', 39492, 4, 41, 99, 20);
insert into artifact (artifactID, anomalyID, name, price, health_change, speed_change, spawn_probability, ownerID) values (65, 65, 'SUN', 16639, 36, 16, 92, null);
insert into artifact (artifactID, anomalyID, name, price, health_change, speed_change, spawn_probability, ownerID) values (66, 66, 'TAPEWORM', 19789, 3, 50, 97, null);
insert into artifact (artifactID, anomalyID, name, price, health_change, speed_change, spawn_probability, ownerID) values (67, 67, 'WRENCHED', 16248, 48, 43, 96, null);
insert into artifact (artifactID, anomalyID, name, price, health_change, speed_change, spawn_probability, ownerID) values (68, 68, 'SCAR', 11307, 22, 38, 20, null);
insert into artifact (artifactID, anomalyID, name, price, health_change, speed_change, spawn_probability, ownerID) values (69, 69, 'FLASH', 3197, 38, 22, 20, null);
insert into artifact (artifactID, anomalyID, name, price, health_change, speed_change, spawn_probability, ownerID) values (70, 70, 'SHARD OF THE MONOLITH', 1025, 13, 36, 59, 83);
