INSERT INTO stalker (humanID, experience, biography) VALUES (106, 4, 'Bandits, Loners');
INSERT INTO stalker (humanID, experience, biography) VALUES (107, 3, 'Mercenaries');
INSERT INTO stalker (humanID, experience, biography) VALUES (108, 2, 'Monolith, Clear Sky');
INSERT INTO stalker (humanID, experience, biography) VALUES (11, 1, 'Loners, Monolith');
INSERT INTO stalker (humanID, experience, biography) VALUES (112, 2, '');
INSERT INTO stalker (humanID, experience, biography) VALUES (114, 0, 'Bandits');
INSERT INTO stalker (humanID, experience, biography) VALUES (115, 1, 'Mercenaries');
INSERT INTO stalker (humanID, experience, biography) VALUES (130, 2, 'Duty');
INSERT INTO stalker (humanID, experience, biography) VALUES (140, 2, '');
INSERT INTO stalker (humanID, experience, biography) VALUES (143, 0, '');
INSERT INTO stalker (humanID, experience, biography) VALUES (145, 1, '');
INSERT INTO stalker (humanID, experience, biography) VALUES (151, 0, '');
INSERT INTO stalker (humanID, experience, biography) VALUES (153, 1, 'Ecologists');
INSERT INTO stalker (humanID, experience, biography) VALUES (154, 3, 'Military');
INSERT INTO stalker (humanID, experience, biography) VALUES (155, 1, 'Duty, Freedom');
INSERT INTO stalker (humanID, experience, biography) VALUES (190, 2, 'Military, Duty');
INSERT INTO stalker (humanID, experience, biography) VALUES (191, 0, 'Duty, Mercenaries');
INSERT INTO stalker (humanID, experience, biography) VALUES (193, 3, '');
INSERT INTO stalker (humanID, experience, biography) VALUES (194, 1, 'Freedom, Mercenaries');
INSERT INTO stalker (humanID, experience, biography) VALUES (20, 3, 'Clear Sky');
INSERT INTO stalker (humanID, experience, biography) VALUES (210, 2, 'Duty, Freedom');
INSERT INTO stalker (humanID, experience, biography) VALUES (216, 4, 'Mercenaries');
INSERT INTO stalker (humanID, experience, biography) VALUES (22, 0, 'Mercenaries, Monolith');
INSERT INTO stalker (humanID, experience, biography) VALUES (228, 4, 'Ecologists');
INSERT INTO stalker (humanID, experience, biography) VALUES (241, 2, '');
INSERT INTO stalker (humanID, experience, biography) VALUES (256, 2, 'Monolith');
INSERT INTO stalker (humanID, experience, biography) VALUES (264, 3, 'Bandits, Duty');
INSERT INTO stalker (humanID, experience, biography) VALUES (265, 0, 'Bandits');
INSERT INTO stalker (humanID, experience, biography) VALUES (273, 2, '');
INSERT INTO stalker (humanID, experience, biography) VALUES (280, 2, '');
INSERT INTO stalker (humanID, experience, biography) VALUES (286, 2, 'Monolith');
INSERT INTO stalker (humanID, experience, biography) VALUES (288, 4, '');
INSERT INTO stalker (humanID, experience, biography) VALUES (297, 4, 'Duty, Freedom');
INSERT INTO stalker (humanID, experience, biography) VALUES (303, 3, 'Duty');
INSERT INTO stalker (humanID, experience, biography) VALUES (314, 3, 'Mercenaries');
INSERT INTO stalker (humanID, experience, biography) VALUES (315, 3, 'Mercenaries, Ecologists');
INSERT INTO stalker (humanID, experience, biography) VALUES (317, 3, 'Mercenaries, Ecologists');
INSERT INTO stalker (humanID, experience, biography) VALUES (32, 1, 'Monolith, Bandits');
INSERT INTO stalker (humanID, experience, biography) VALUES (322, 1, 'Freedom');
INSERT INTO stalker (humanID, experience, biography) VALUES (327, 2, 'Military');
INSERT INTO stalker (humanID, experience, biography) VALUES (335, 3, 'Military, Freedom');
INSERT INTO stalker (humanID, experience, biography) VALUES (349, 1, '');
INSERT INTO stalker (humanID, experience, biography) VALUES (351, 3, '');
INSERT INTO stalker (humanID, experience, biography) VALUES (358, 1, '');
INSERT INTO stalker (humanID, experience, biography) VALUES (360, 3, '');
INSERT INTO stalker (humanID, experience, biography) VALUES (362, 2, 'Clear Sky, Bandits');
INSERT INTO stalker (humanID, experience, biography) VALUES (383, 0, '');
INSERT INTO stalker (humanID, experience, biography) VALUES (392, 2, '');
INSERT INTO stalker (humanID, experience, biography) VALUES (4, 0, '');
INSERT INTO stalker (humanID, experience, biography) VALUES (41, 2, 'Duty');
INSERT INTO stalker (humanID, experience, biography) VALUES (417, 1, 'Freedom, Ecologists');
INSERT INTO stalker (humanID, experience, biography) VALUES (42, 4, 'Monolith, Military');
INSERT INTO stalker (humanID, experience, biography) VALUES (424, 3, 'Clear Sky, Bandits');
INSERT INTO stalker (humanID, experience, biography) VALUES (426, 1, 'Mercenaries');
INSERT INTO stalker (humanID, experience, biography) VALUES (429, 0, '');
INSERT INTO stalker (humanID, experience, biography) VALUES (444, 3, '');
INSERT INTO stalker (humanID, experience, biography) VALUES (447, 0, '');
INSERT INTO stalker (humanID, experience, biography) VALUES (448, 4, '');
INSERT INTO stalker (humanID, experience, biography) VALUES (460, 1, 'Clear Sky, Duty');
INSERT INTO stalker (humanID, experience, biography) VALUES (475, 3, '');
INSERT INTO stalker (humanID, experience, biography) VALUES (478, 3, '');
INSERT INTO stalker (humanID, experience, biography) VALUES (486, 2, '');
INSERT INTO stalker (humanID, experience, biography) VALUES (492, 1, 'Clear Sky');
INSERT INTO stalker (humanID, experience, biography) VALUES (513, 3, 'Ecologists');
INSERT INTO stalker (humanID, experience, biography) VALUES (530, 4, 'Loners');
INSERT INTO stalker (humanID, experience, biography) VALUES (535, 0, '');
INSERT INTO stalker (humanID, experience, biography) VALUES (536, 4, 'Loners, Monolith');
INSERT INTO stalker (humanID, experience, biography) VALUES (539, 1, 'Freedom, Loners');
INSERT INTO stalker (humanID, experience, biography) VALUES (548, 2, 'Bandits, Duty');
INSERT INTO stalker (humanID, experience, biography) VALUES (551, 4, 'Mercenaries, Monolith');
INSERT INTO stalker (humanID, experience, biography) VALUES (557, 3, 'Military');
INSERT INTO stalker (humanID, experience, biography) VALUES (562, 4, 'Mercenaries');
INSERT INTO stalker (humanID, experience, biography) VALUES (590, 2, 'Bandits, Freedom');
INSERT INTO stalker (humanID, experience, biography) VALUES (596, 1, '');
INSERT INTO stalker (humanID, experience, biography) VALUES (597, 0, 'Loners, Ecologists');
INSERT INTO stalker (humanID, experience, biography) VALUES (602, 3, 'Military');
INSERT INTO stalker (humanID, experience, biography) VALUES (612, 2, 'Freedom');
INSERT INTO stalker (humanID, experience, biography) VALUES (618, 1, 'Bandits');
INSERT INTO stalker (humanID, experience, biography) VALUES (619, 1, '');
INSERT INTO stalker (humanID, experience, biography) VALUES (623, 4, 'Monolith');
INSERT INTO stalker (humanID, experience, biography) VALUES (626, 4, 'Loners, Monolith');
INSERT INTO stalker (humanID, experience, biography) VALUES (630, 1, 'Military, Duty');
INSERT INTO stalker (humanID, experience, biography) VALUES (642, 2, 'Ecologists');
INSERT INTO stalker (humanID, experience, biography) VALUES (649, 0, 'Mercenaries');
INSERT INTO stalker (humanID, experience, biography) VALUES (65, 3, 'Clear Sky');
INSERT INTO stalker (humanID, experience, biography) VALUES (655, 2, 'Bandits');
INSERT INTO stalker (humanID, experience, biography) VALUES (660, 4, '');
INSERT INTO stalker (humanID, experience, biography) VALUES (665, 3, '');
INSERT INTO stalker (humanID, experience, biography) VALUES (68, 3, '');
INSERT INTO stalker (humanID, experience, biography) VALUES (700, 4, 'Military, Duty');
INSERT INTO stalker (humanID, experience, biography) VALUES (704, 3, '');
INSERT INTO stalker (humanID, experience, biography) VALUES (706, 1, 'Monolith, Clear Sky');
INSERT INTO stalker (humanID, experience, biography) VALUES (71, 2, 'Bandits, Duty');
INSERT INTO stalker (humanID, experience, biography) VALUES (712, 0, 'Mercenaries, Clear Sky');
INSERT INTO stalker (humanID, experience, biography) VALUES (714, 2, 'Bandits');
INSERT INTO stalker (humanID, experience, biography) VALUES (718, 3, '');
INSERT INTO stalker (humanID, experience, biography) VALUES (725, 4, '');
INSERT INTO stalker (humanID, experience, biography) VALUES (735, 3, 'Bandits, Duty');
INSERT INTO stalker (humanID, experience, biography) VALUES (741, 4, '');
INSERT INTO stalker (humanID, experience, biography) VALUES (76, 3, 'Clear Sky, Duty');
INSERT INTO stalker (humanID, experience, biography) VALUES (761, 3, 'Duty');
INSERT INTO stalker (humanID, experience, biography) VALUES (764, 4, 'Monolith, Bandits');
INSERT INTO stalker (humanID, experience, biography) VALUES (768, 2, '');
INSERT INTO stalker (humanID, experience, biography) VALUES (774, 2, 'Clear Sky, Bandits');
INSERT INTO stalker (humanID, experience, biography) VALUES (776, 4, 'Ecologists');
INSERT INTO stalker (humanID, experience, biography) VALUES (788, 2, 'Freedom, Ecologists');
INSERT INTO stalker (humanID, experience, biography) VALUES (789, 3, 'Clear Sky');
INSERT INTO stalker (humanID, experience, biography) VALUES (803, 3, 'Clear Sky');
INSERT INTO stalker (humanID, experience, biography) VALUES (809, 1, 'Duty, Mercenaries');
INSERT INTO stalker (humanID, experience, biography) VALUES (824, 1, 'Military');
INSERT INTO stalker (humanID, experience, biography) VALUES (830, 2, 'Freedom, Loners');
INSERT INTO stalker (humanID, experience, biography) VALUES (833, 1, 'Duty, Freedom');
INSERT INTO stalker (humanID, experience, biography) VALUES (834, 4, 'Loners, Mercenaries');
INSERT INTO stalker (humanID, experience, biography) VALUES (837, 1, 'Loners, Mercenaries');
INSERT INTO stalker (humanID, experience, biography) VALUES (841, 3, 'Mercenaries');
INSERT INTO stalker (humanID, experience, biography) VALUES (845, 0, 'Loners, Monolith');
INSERT INTO stalker (humanID, experience, biography) VALUES (852, 4, 'Bandits, Duty');
INSERT INTO stalker (humanID, experience, biography) VALUES (860, 3, 'Freedom, Mercenaries');
INSERT INTO stalker (humanID, experience, biography) VALUES (870, 4, 'Military, Bandits');
INSERT INTO stalker (humanID, experience, biography) VALUES (876, 2, 'Duty, Loners');
INSERT INTO stalker (humanID, experience, biography) VALUES (883, 2, 'Military');
INSERT INTO stalker (humanID, experience, biography) VALUES (887, 2, 'Duty, Loners');
INSERT INTO stalker (humanID, experience, biography) VALUES (889, 4, 'Military');
INSERT INTO stalker (humanID, experience, biography) VALUES (901, 0, 'Ecologists, Military');
INSERT INTO stalker (humanID, experience, biography) VALUES (913, 4, 'Bandits, Freedom');
INSERT INTO stalker (humanID, experience, biography) VALUES (925, 1, 'Duty');
INSERT INTO stalker (humanID, experience, biography) VALUES (931, 1, '');
INSERT INTO stalker (humanID, experience, biography) VALUES (933, 1, 'Mercenaries, Clear Sky');
INSERT INTO stalker (humanID, experience, biography) VALUES (935, 3, 'Loners');
INSERT INTO stalker (humanID, experience, biography) VALUES (936, 4, '');
INSERT INTO stalker (humanID, experience, biography) VALUES (945, 2, '');
INSERT INTO stalker (humanID, experience, biography) VALUES (947, 3, 'Monolith, Clear Sky');
INSERT INTO stalker (humanID, experience, biography) VALUES (963, 3, '');
INSERT INTO stalker (humanID, experience, biography) VALUES (964, 0, '');
INSERT INTO stalker (humanID, experience, biography) VALUES (975, 3, 'Bandits, Freedom');
INSERT INTO stalker (humanID, experience, biography) VALUES (986, 2, '');
INSERT INTO stalker (humanID, experience, biography) VALUES (987, 0, '');
INSERT INTO stalker (humanID, experience, biography) VALUES (991, 1, 'Freedom');

INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (118, 3, 4);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (12, 3, 2);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (129, 3, 1);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (13, 3, 4);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (132, 2, 4);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (133, 3, 7);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (136, 6, 9);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (137, 2, 4);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (142, 0, 1);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (149, 1, 6);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (150, 6, 6);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (16, 0, 2);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (162, 4, 4);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (163, 3, 3);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (165, 0, 6);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (167, 2, 1);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (170, 3, 1);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (173, 6, 8);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (175, 3, 8);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (178, 3, 4);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (183, 2, 7);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (185, 5, 1);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (186, 5, 1);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (189, 4, 8);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (196, 0, 4);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (2, 2, 2);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (201, 3, 7);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (209, 2, 6);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (213, 0, 3);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (214, 5, 8);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (221, 5, 3);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (222, 4, 1);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (227, 2, 1);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (23, 5, 6);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (231, 4, 6);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (233, 1, 6);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (234, 1, 5);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (24, 0, 9);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (244, 6, 2);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (245, 3, 3);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (249, 1, 6);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (250, 4, 8);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (253, 6, 9);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (257, 2, 6);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (258, 0, 4);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (260, 3, 3);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (269, 1, 8);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (270, 3, 7);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (28, 3, 5);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (282, 1, 9);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (283, 3, 3);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (284, 0, 1);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (291, 6, 9);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (296, 3, 9);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (308, 3, 5);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (310, 3, 2);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (311, 0, 7);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (319, 2, 3);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (320, 6, 6);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (324, 6, 2);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (325, 4, 4);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (329, 1, 3);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (334, 5, 9);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (337, 4, 1);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (344, 5, 7);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (353, 1, 5);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (361, 2, 3);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (364, 1, 5);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (368, 3, 8);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (374, 1, 5);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (377, 2, 3);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (38, 5, 1);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (394, 6, 7);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (398, 2, 8);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (399, 4, 3);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (405, 6, 8);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (409, 1, 5);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (411, 3, 7);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (412, 4, 7);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (422, 5, 7);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (423, 0, 7);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (431, 0, 2);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (435, 3, 3);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (436, 2, 9);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (440, 6, 9);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (451, 5, 9);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (453, 1, 9);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (459, 1, 1);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (463, 5, 9);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (464, 2, 2);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (470, 1, 1);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (480, 3, 9);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (484, 1, 5);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (488, 3, 8);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (490, 5, 6);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (498, 6, 8);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (499, 3, 2);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (5, 6, 5);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (502, 2, 1);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (509, 3, 7);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (510, 4, 4);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (516, 2, 6);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (520, 6, 3);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (522, 6, 1);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (524, 6, 4);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (528, 1, 6);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (529, 4, 7);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (532, 4, 2);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (533, 1, 6);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (537, 0, 9);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (541, 0, 4);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (543, 3, 7);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (544, 0, 1);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (546, 5, 6);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (55, 5, 3);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (561, 0, 5);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (566, 6, 4);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (573, 5, 7);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (574, 0, 4);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (578, 3, 1);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (585, 5, 2);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (587, 0, 4);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (589, 2, 6);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (59, 0, 4);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (591, 3, 6);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (592, 5, 4);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (599, 5, 5);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (600, 0, 5);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (601, 5, 1);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (607, 0, 4);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (61, 4, 4);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (634, 1, 3);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (635, 4, 1);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (651, 6, 8);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (652, 4, 5);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (659, 5, 5);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (662, 2, 6);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (663, 0, 8);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (664, 4, 9);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (667, 2, 7);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (677, 5, 4);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (678, 2, 1);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (679, 5, 8);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (680, 2, 6);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (682, 4, 9);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (686, 1, 3);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (687, 1, 1);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (691, 4, 1);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (698, 0, 2);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (703, 0, 5);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (705, 2, 9);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (719, 3, 9);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (72, 2, 6);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (723, 2, 3);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (724, 6, 2);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (728, 5, 5);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (74, 4, 2);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (743, 0, 9);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (746, 3, 2);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (749, 1, 3);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (751, 5, 5);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (763, 5, 8);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (765, 6, 6);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (767, 6, 2);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (775, 1, 8);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (780, 5, 9);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (782, 2, 9);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (787, 0, 5);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (793, 3, 3);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (794, 0, 3);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (806, 4, 8);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (807, 4, 8);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (808, 6, 5);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (810, 3, 4);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (813, 6, 7);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (816, 4, 7);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (817, 5, 7);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (829, 5, 6);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (831, 2, 3);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (832, 0, 9);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (839, 0, 6);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (842, 0, 9);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (848, 5, 9);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (854, 2, 2);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (855, 1, 3);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (857, 2, 7);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (859, 5, 9);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (86, 4, 5);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (861, 2, 2);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (865, 2, 6);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (866, 4, 8);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (874, 2, 2);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (877, 5, 2);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (88, 3, 1);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (894, 0, 6);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (9, 5, 5);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (902, 2, 6);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (903, 3, 6);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (904, 1, 7);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (906, 0, 1);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (909, 3, 6);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (910, 6, 7);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (914, 0, 3);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (919, 2, 2);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (920, 0, 7);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (926, 4, 1);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (927, 2, 6);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (929, 1, 5);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (932, 1, 2);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (939, 5, 6);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (941, 6, 1);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (942, 3, 5);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (944, 2, 9);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (949, 5, 6);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (952, 3, 8);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (955, 0, 8);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (956, 1, 3);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (962, 4, 5);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (965, 3, 8);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (968, 6, 6);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (970, 2, 2);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (971, 2, 5);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (972, 1, 4);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (973, 4, 5);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (976, 6, 7);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (983, 3, 8);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (99, 5, 7);
INSERT INTO warrior (humanID, experience, mother_groupid) VALUES (992, 3, 8);

INSERT INTO trader (humanID, mother_groupid) VALUES (160, 7);
INSERT INTO trader (humanID, mother_groupid) VALUES (211, 5);
INSERT INTO trader (humanID, mother_groupid) VALUES (278, 2);
INSERT INTO trader (humanID, mother_groupid) VALUES (450, 1);
INSERT INTO trader (humanID, mother_groupid) VALUES (504, 8);
INSERT INTO trader (humanID, mother_groupid) VALUES (579, 7);
INSERT INTO trader (humanID, mother_groupid) VALUES (608, 4);
INSERT INTO trader (humanID, mother_groupid) VALUES (621, 6);
INSERT INTO trader (humanID, mother_groupid) VALUES (684, 1);
INSERT INTO trader (humanID, mother_groupid) VALUES (73, 4);
INSERT INTO trader (humanID, mother_groupid) VALUES (742, 5);
INSERT INTO trader (humanID, mother_groupid) VALUES (75, 7);
INSERT INTO trader (humanID, mother_groupid) VALUES (762, 5);
INSERT INTO trader (humanID, mother_groupid) VALUES (791, 4);
INSERT INTO trader (humanID, mother_groupid) VALUES (792, 1);
INSERT INTO trader (humanID, mother_groupid) VALUES (827, 2);
INSERT INTO trader (humanID, mother_groupid) VALUES (891, 6);

INSERT INTO scientist (humanID, specialization, mission) VALUES (1001, 'physicist', 'explain Monolith');
